export const USER_PRESENCE_STATUS = {
  ONLINE: "ONLINE",
  OFFLINE: "OFFLINE",
  AWAY: "AWAY",
  IN_CALL: "IN_CALL",
  AVAILABLE: "AVAILABLE",
  BUSY: "BUSY",
};

export const MESSAGE_STATUS = {
  SENT: "SENT",
  DELIVERED: "DELIVERED",
  SEEN: "SEEN",
};

export const REQUEST_STATUS = {
  SENT: "SENT",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
};

export const ENTRY_TYPE = {
  CHAT_ENTRY: "CHAT ENTRY",
  SESSION_ENTRY: "SESSION_ENTRY",
  MESSAGE_ENTRY: "MESSAGE_ENTRY",
  REQUEST_ENTRY: "REQUEST_ENTRY",
};
