export const USER_PRESENCE_STATUS = {
  ONLINE: "ONLINE",
  OFFLINE: "OFFLINE",
  AWAY: "AWAY",
  IN_CALL: "IN_CALL",
  AVAILABLE: "AVAILABLE",
  BUSY: "BUSY",
};

export const MESSAGE_STATUS = {
  SENT: "SENT",
  DELIVERED: "DELIVERED",
  SEEN: "SEEN",
};

export const CALL_KIND = {
  INITIATE: "INITIATE",
  ANSWER: "ANSWER",
  DECLINED: "DECLINED",
  CANCELLED: "CANCELLED",
  RECORDING: "RECORDING",
  ENDED: "ENDED",
  MUTE: "MUTE",
  UNMUTE: "UNMUTE",
  HOLD: "HOLD",
  RESUME: "RESUME",
  PAUSE_VIDEO: "PAUSE_VIDEO",
  RESUME_VIDEO: "RESUME_VIDEO",
};

export const REQUEST_STATUS = {
  SENT: "SENT",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
};

export const ENTRY_TYPE = {
  CHAT_ENTRY: "CHAT_ENTRY",
  SESSION_ENTRY: "SESSION_ENTRY",
  MESSAGE_ENTRY: "MESSAGE_ENTRY",
  REQUEST_ENTRY: "REQUEST_ENTRY",
};
